### ISSUE TITLE
Mysterious CUDA error

### ISSUE THREAD

**Issue by ThomasHeap** [alan-ppl/alan#20]
I and Sam have both noticed that sometimes we will get errors of the following form:

```
#Repeated a bunch of times at beginning of log file
/opt/conda/conda-bld/pytorch_1702400366987/work/aten/src/ATen/native/cuda/MultinomialKernel.cu:112: binarySearchForMultinomial: block: [0,0,0], thread: [94,0,0] Assertion `cumdist[size - 1]$

#Rest of log file up until error triggers

Iter 150. Elbo: -1569.542, PredLL: -1725.991
num_run: 0 K: 30 lr: 0.3 failed at iteration 200 with exception CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
.
Error executing job with overrides: ['model=bus_breakdown', 'method=qem', 'Ks=[30]', 'lrs=[0.3]']
Traceback (most recent call last):
  File "/user/home/cp20141/repos/alan/examples/runner.py", line 87, in run_experiment
    t.manual_seed(num_run)
  File "/user/home/cp20141/miniconda3/envs/alan/lib/python3.10/site-packages/torch/random.py", line 40, in manual_seed
    torch.cuda.manual_seed_all(seed)
  File "/user/home/cp20141/miniconda3/envs/alan/lib/python3.10/site-packages/torch/cuda/random.py", line 124, in manual_seed_all
    _lazy_call(cb, seed_all=True)
  File "/user/home/cp20141/miniconda3/envs/alan/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_call
    callable()
  File "/user/home/cp20141/miniconda3/envs/alan/lib/python3.10/site-packages/torch/cuda/random.py", line 122, in cb
    default_generator.manual_seed(seed)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by LaurenceA** [comment]
This issue:
https://github.com/ultralytics/ultralytics/issues/4728
Seems to suggest the problem is:

> The error message you are seeing, RuntimeError: CUDA error: device-side assert triggered, is typical when there may be an issue with the indices used in operations like scatter, gather, etc., most commonly indicating that an index is out of the given range.

That means I'd expect the error to turn up only when importance sampling.  Is that true?

**Comment by ThomasHeap** [comment]
Its difficult to tell at which point of the program this error actually occurs. Let me try and replicate it and I'll see.

**Comment by LaurenceA** [comment]
I have a terrible feeling we're triggering a very rare bug in
PyTorch's multinomial sampling here.

**Comment by ThomasHeap** [comment]
Things to try:
 - Catch error before hand by checking multinomial logits
 - Move things to CPU during sampling?

**Comment by ThomasHeap** [comment]
This actually isn't so mysterious, on cpu this error is just 

``
RuntimeError: invalid multinomial distribution (encountering probability entry < 0)
``

But on CUDA this triggers a device side error. 

By putting some asserts before multinomial sampling in reduce_Ks.py and SampleNonMP.py we should catch this error and not disrupt our training scripts.
