### ISSUE TITLE
Do we need grouping in both P and Q?

### ISSUE THREAD

**Issue by ThomasHeap** [alan-ppl/alan#21]
Investigate this...

**Comment by ThomasHeap** [comment]
If we only group in P memory consumption is higher than grouping both P and Q. I've confirmed this by testing the covid model with both configurations. Question: Should this be the case? Should Q just inherit P's grouping?

**Comment by LaurenceA** [comment]
Hmm ... that really shouldn't happen.

**Comment by LaurenceA** [comment]
Can you put together a minimum working example + work out whether there are
difference in other places (e.g. ELBO when we use same random seed)?
